[package]
name = "sci-all-streams-api"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
diesel = "2"
diesel_migrations = "2"

[dependencies.rocket_db_pools]
version = "0.2.0"
features = ["diesel_mysql"]